### ISSUE TITLE
Make Idle Timer Optional

### ISSUE THREAD

**Issue by MichaelXavier** [cdepillabout/break-time#28]
Would it be possible to make the idle timer optional? I intend on using this in a secondary machine that sort of acts as an external screen while I work on a different machine, thus an idle timeout doesn't really make sense.

**Comment by cdepillabout** [comment]
I'd be happy to accept a PR for this.

Here's how I'd imagine someone would go about implementing this:

1. First, add a config option for disabling the idle timer.  Here is the data type that defines the settings:

    https://github.com/cdepillabout/break-time/blob/6460ab7ad6359cbb454b679a05b2761b264933f4/src/config.rs#L44-L56

2. Conditionally stop the idle detector from running.  Here is the code that spawns the idle detector:

    https://github.com/cdepillabout/break-time/blob/6460ab7ad6359cbb454b679a05b2761b264933f4/src/scheduler.rs#L134-L136

    Or possibly modify the IdleDetector code to not send any messages.  I'm not sure what is the better choice here.

(Although keep in mind at this point that I haven't hacked on this library in a year or so, so if you dig into the code, maybe there is a better way to do this.)

**Comment by cdepillabout** [comment]
I ended up wanting this functionality as well, so I implemented it in #31.

Now, you can add a line like `idle_detection_enabled = false` to the top-level of your `~/.config/break-time/config.toml` config file and the idle detection functionality will be ignored.

You can also enable/disable this at run-time if you right click on the status bar icon.
